# Generated by Django 5.2.1 on 2025-05-12 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_goat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diseas',
            name='cause',
            field=models.TextField(default=False),
        ),
        migrations.AddField(
            model_name='diseas',
            name='sympton',
            field=models.TextField(default=False),
        ),
        migrations.AddField(
            model_name='diseas',
            name='title',
            field=models.CharField(default='Unknow', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diseas',
            name='treatment',
            field=models.TextField(default=False),
        ),
    ]
