# Generated by Django 5.2.1 on 2025-05-14 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_goat', '0002_diseas_cause_diseas_sympton_diseas_title_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Diseas',
            new_name='Diseases',
        ),
    ]
