# Generated by Django 5.2.1 on 2025-06-28 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_goat', '0004_diseases_img_relative_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diseases',
            name='img_relative_url',
        ),
        migrations.AddField(
            model_name='diseases',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='disease_images/'),
        ),
    ]
