# Generated by Django 5.2.1 on 2025-05-16 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_goat', '0003_rename_diseas_diseases'),
    ]

    operations = [
        migrations.AddField(
            model_name='diseases',
            name='img_relative_url',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
