# Generated by Django 5.2.1 on 2025-07-13 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_goat', '0005_remove_diseases_img_relative_url_diseases_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoatStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_goats', models.PositiveIntegerField(default=0, verbose_name='ประชากรแพะในประเทศไทย')),
                ('total_farmers', models.PositiveIntegerField(default=0, verbose_name='เกษตรกรในประเทศไทย')),
                ('goats_south', models.PositiveIntegerField(default=0, verbose_name='ประชากรแพะในชายแดนใต้')),
                ('farmers_south', models.PositiveIntegerField(default=0, verbose_name='เกษตรกรในชายแดนใต้')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'ข้อมูลสถิติแพะ',
                'verbose_name_plural': 'ข้อมูลสถิติแพะ',
            },
        ),
        migrations.AlterField(
            model_name='diseases',
            name='cause',
            field=models.TextField(blank=True, default='ข้อมูลไม่ระบุ', null=True),
        ),
        migrations.AlterField(
            model_name='diseases',
            name='sympton',
            field=models.TextField(blank=True, default='ข้อมูลไม่ระบุ', null=True),
        ),
        migrations.AlterField(
            model_name='diseases',
            name='treatment',
            field=models.TextField(blank=True, default='ข้อมูลไม่ระบุ', null=True),
        ),
    ]
