# Generated by Django 5.2 on 2025-09-08 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_goat', '0006_goatstatistics_alter_diseases_cause_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diseases',
            old_name='sympton',
            new_name='symptom',
        ),
        migrations.AlterField(
            model_name='goatstatistics',
            name='farmers_south',
            field=models.PositiveIntegerField(default=0, verbose_name='เกษตรกรในสามจังหวัดชายแดนใต้'),
        ),
        migrations.AlterField(
            model_name='goatstatistics',
            name='goats_south',
            field=models.PositiveIntegerField(default=0, verbose_name='ประชากรแพะในสามจังหวัดชายแดนใต้'),
        ),
    ]
