# Generated by Django 5.2 on 2025-09-22 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_goat', '0007_rename_sympton_diseases_symptom_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diseases',
            options={'verbose_name': 'ข้อมูลโรคของแพะ', 'verbose_name_plural': 'ข้อมูลโรคของแพะ'},
        ),
        migrations.AlterField(
            model_name='diseases',
            name='cause',
            field=models.TextField(blank=True, default='เพิ่มข้อมูล', null=True),
        ),
        migrations.AlterField(
            model_name='diseases',
            name='symptom',
            field=models.TextField(blank=True, default='เพิ่มข้อมูล', null=True),
        ),
        migrations.AlterField(
            model_name='diseases',
            name='treatment',
            field=models.TextField(blank=True, default='เพิ่มข้อมูล', null=True),
        ),
    ]
