# Generated by Django 5.2.4 on 2025-09-25 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_goat', '0008_alter_diseases_options_alter_diseases_cause_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diseases',
            name='title2',
            field=models.CharField(default='default title', max_length=50),
        ),
    ]
