# Generated by Django 5.2.4 on 2025-09-25 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_goat', '0009_diseases_title2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diseases',
            name='title2',
        ),
    ]
